pipeline:
  name: balu-funcapp
  identifier: balufuncapp
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: balugitapp
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: baluakscluster
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: baluacr
                    image: baluhaness.azurecr.io/node-azurecli:latest
                    shell: Sh
                    command: |-
                      npm install
                      func pack       
                      zip -r function.zip .
                    envVariables:
                      ARM_CLIENT_ID: <+secrets.getValue("client_id_balu")>
                      ARM_CLIENT_SECRET: <+secrets.getValue("client_secret_balu")>
                      ARM_SUBSCRIPTION_ID: <+secrets.getValue("subscription_id_balu")>
                      ARM_TENANT_ID: <+secrets.getValue("tenant_id_balu")>
